### ISSUE TITLE
为什么找不到classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'

### ISSUE THREAD

**Issue by 1990MyLove** [2tu/crop#1]
急需解决啊，求指教
我在root build.gradle添加
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
在library添加
apply plugin: 'com.github.dcendents.android-maven'
group='com.github.1990MyLove
sync之后，为什么报错，在我的D:\software\Android Studio\gradle\m2repository\com\github......
找不到android-maven-gradle-plugin:1.3.pom和android-maven-gradle-plugin:1.3.jar

**Comment by zongbintu** [comment]
https://jitpack.io/docs/ANDROID/
